import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'

export default function Home() {
  const handleOnBannerClick = () => {

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>coffee cornnoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        </h1>
          <Banner buttonText="View stores nearby" 
          handleOnClick={handleOnBannerClick} 
          />

          <div className={styles.heroImage}>
            <Image src='/static/hero-image.png' alt="coffe cat" width={700} height={700} />
          </div>

          
      </main>
    </div>
  )
}
